apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCerk1vPazzA+bhlrXepiEZh8ipGobdmsE2ZnGQ5Kgak8quBQBYX/c1AbSnHMSO9rXANp4HYBy1lKJTCdQJ66BZM+6v4ZV3jyVRa8CVGssBbe44f/DuT77bz2xCI8xDDWrtBnuc7HC0OC/8WgZCf9x3ZcfLLMPbC409NZTIF4nCEqOGIiQDJMT+CfVcozaMBEE3zDXPhiOGHxrgetUdH4fEhXWCYLsQkIPyfBf11GvZuoio4bMocCpoT2NoNaF0EToB/S434XcvVSaEIelzuuT+G2BpCdsPZdTwrsIV0lHpQt40TqoKp506koGcdoCu9ZR0n/k3g5iIKDcXj2lUp5i9XqFH97e5eNMbHlK2P71/JNR6Rw67zlcYMcQhhahUQKtMp1ZxZ9hoB1Jlbqrilnl+e5g11Rslb+50Lak9vWfDzgik0MbQck50C+7kVgTRx8zVaZ9NapPvsan6+EpOy6eMzmJFbHexBSvg8tUT9Zc1EED6UAc46eEdKmZY9DcIo8yQKjXmL5s6cNWYNTeVu3L9dnWFLbTwFyf13NewUy5utC+r5v5TDT2LoGJBMhi0+8u+jwILF7dAByN2mieTT5nNqBCWvQFr8vuMfPikb4yBAEnmdPhBWJ9pAFuzFHKP2wDvwyJ7YkyWCFW7ZP6X3CeVS65z1y+Rbdz8dpJ+KTYzJqFWxCULi3YLDXpDHVmkH9kQk4SXFQFNQg==
    DB_USER: AgBTkue8zdcGHrkONgX2rtaRShewcCar6aK0OIXtCMBnFpgYB8BkvF7i+5GfJL7Hr1e1FK4Y8WGk4y10itpDG1wyI3qTy0OVpWKCYtgB4c/nasbEHB+mlluZ6w8Yv1MXu9HPtb3K0NIRH87lYFksjIEA3a04kpBJXYk6DoVhrfyJYRgOumDjYQyHDA/udxJ9QpRIkIDpuKhT2yDKbrDRpp7J4jalNSOTLQbZsLqYECSkF36qufteJS6OK5oEqDH5ZPHSNMPGGmby7PIbpy3aL0pxU02O0rH9xo500mGSBCPfz6S8cNXCmw+sfEBMJFFCfDFf4PuRYyFjPq5IRo575wTuF4FeFa82JUvcjhbR1ScVRqhGX7VzdBCfFMZwpA+/wZafSnjeddPEUYuxaYuavnhdidOWxNt0cALyjyS5ydi9ZDn4whH9lqaHNpZhdzm3gOIzR2ef3LjqKoy0DXikDLhhm8kNYRRPFHjU0xGE7mYus8n30j6Ys3a1v5kuFIjg024GTnfbM7iowOafkSpMPXnnEiP2P9nb4jvLwrA2NUQsZviOlYb/VGweOkptRMDhqstF1dDdruTLPjfuzvRmZiVIsx/OQ0FABRSR8IMvo0EEpN3L7B8jqS/lik3FjSvu8J4wDvu1ROhTndnUwOqBL1zUvhCBAhlY2rAtxtUJi/JlkfPFE7O7hdd8uLIqyHJKUOP572OhVxR/WA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

